import { LibraryStoryItem, AchievementBadge, DayStreakItem } from '../types/library';

export const TRENDING_STORIES: LibraryStoryItem[] = [
  {
    id: '1',
    title: 'Lâu Đài Kẹo Ngọt Trên Mây',
    description: 'Cùng bé An và thỏ Trắng học cách sẻ chia kẹo ngọt để giải cứu vương quốc trên mây khỏi nguy cơ bị rã tan...',
    duration: '10 phút',
    tag: 'AI & Bé An sáng tạo',
    badge: 'AI & Bé An',
    badgeBg: 'bg-amber-100 dark:bg-amber-900/40 text-amber-800 dark:text-amber-200',
    listens: '4.3k',
    rating: 4.9,
    imageUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=600&auto=format&fit=crop',
    isFavorite: true,
  },
  {
    id: '2',
    title: 'Khủng Long Dino Đi Tìm Mẹ',
    description: 'Hành trình dũng cảm băng qua thung lũng đá núi lửa và kết bạn với những chú rồng biết bay thông thái...',
    duration: '8 phút',
    tag: 'Âm thanh sống động',
    badge: 'Âm thanh sống động',
    badgeBg: 'bg-orange-100 dark:bg-orange-900/40 text-orange-800 dark:text-orange-200',
    listens: '9.2k',
    rating: 5.0,
    imageUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?q=80&w=600&auto=format&fit=crop',
    isFavorite: true,
  },
  {
    id: '3',
    title: 'Chuyến Phiêu Lưu Đáy Biển Của Rùa Con',
    description: 'Bài học về bảo vệ rạn san hô và dọn sạch rác thải nhựa cùng những người bạn cá heo vui tính dưới đại dương...',
    duration: '12 phút',
    tag: 'Giáo dục bảo vệ biển',
    badge: 'Bảo vệ biển',
    badgeBg: 'bg-cyan-100 dark:bg-cyan-900/40 text-cyan-800 dark:text-cyan-200',
    listens: '2.7k',
    rating: 4.8,
    imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=600&auto=format&fit=crop',
    isFavorite: true,
  },
  {
    id: '4',
    title: 'Chiếc Ô Bay Của Phù Thủy Nhỏ',
    description: 'Chiếc ô thần kỳ có thể che mưa cho cả khu rừng và biến những hạt mưa thành kẹo ngọt màu sắc làm quà cho động vật...',
    duration: '7 phút',
    tag: 'Trí tưởng tượng bay bổng',
    badge: 'Pháp thuật',
    badgeBg: 'bg-purple-100 dark:bg-purple-900/40 text-purple-800 dark:text-purple-200',
    listens: '5.1k',
    rating: 4.9,
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=600&auto=format&fit=crop',
    isFavorite: true,
  },
];

export const LIBRARY_CREATED_STORIES: LibraryStoryItem[] = [
  {
    id: 'cr-1',
    badge: '🤖 AI Mini & Bé Bo',
    badgeBg: 'bg-emerald-100 dark:bg-emerald-900/40 text-emerald-700 dark:text-emerald-300',
    tag: 'Sáng tạo ngày 12/03 • 8 phút nghe',
    title: 'Chiếc Bánh Quy Biết Bay Của Thỏ Bông',
    description: 'Chú thỏ Bông nhặt được số phép thuật nấu nướng, nướng ra chiếc bánh quy có cánh bay khắp xóm làng...',
    imageUrl: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?q=80&w=600&auto=format&fit=crop',
    isFavorite: true,
  },
  {
    id: 'cr-2',
    badge: '🎨 Bé Bo đồng tác giả',
    badgeBg: 'bg-amber-100 dark:bg-amber-900/40 text-amber-700 dark:text-amber-300',
    tag: 'Sáng tạo ngày 09/03 • 12 phút nghe',
    title: 'Khủng Long Dino Đi Tìm Mẹ Thần Tiên',
    description: 'Dino dũng cảm chế tạo đá bay kỳ ảo rực rỡ nắng lồng, vượt qua rừng thung thạch ngọt ngào để tìm thấy mẹ...',
    imageUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?q=80&w=600&auto=format&fit=crop',
    isFavorite: true,
  },
];

export const LIBRARY_FAVORITE_STORIES: LibraryStoryItem[] = [
  {
    id: 'fav-1',
    badge: '🌙 Ru ngủ sâu',
    badgeBg: 'bg-indigo-100 dark:bg-indigo-900/40 text-indigo-700 dark:text-indigo-300',
    tag: '15 phút • Sóng Alpha',
    title: 'Chuyến Du Hành Vào Giấc Mộng',
    description: 'Giai điệu du dương hòa cùng giọng hát ru vỗ về bé vào giấc ngủ ngon êm đềm...',
    rating: 5.0,
    imageUrl: 'https://images.unsplash.com/photo-1532693322450-2cb5c511067d?q=80&w=600&auto=format&fit=crop',
    isFavorite: true,
  },
  {
    id: 'fav-2',
    badge: '🌲 Giáo dục tâm hồn',
    badgeBg: 'bg-emerald-100 dark:bg-emerald-900/40 text-emerald-700 dark:text-emerald-300',
    tag: '10 phút • Giọng ấm',
    title: 'Bác Sĩ Cú Mèo & Khu Rừng Xanh',
    description: 'Bác sĩ Cú Mèo chữa lành tâm hồn thỏ con và dạy bài học yêu thương bạn bè...',
    rating: 4.9,
    imageUrl: 'https://images.unsplash.com/photo-1543549790-8b5f4a028cfb?q=80&w=600&auto=format&fit=crop',
    isFavorite: true,
  },
  {
    id: 'fav-3',
    badge: '🪄 Phép thuật',
    badgeBg: 'bg-amber-100 dark:bg-amber-900/40 text-amber-700 dark:text-amber-300',
    tag: '12 phút • Nghe trước ngủ',
    title: 'Chiếc Ô Bay Của Phù Thủy Nhỏ',
    description: 'Chiếc ô thần kỳ che chở muôn loài và mở ra vùng đất diệu kỳ cho ước mơ của bé...',
    rating: 4.9,
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=600&auto=format&fit=crop',
    isFavorite: true,
  },
  {
    id: 'fav-4',
    badge: '🌙 Ru ngủ sâu',
    badgeBg: 'bg-indigo-100 dark:bg-indigo-900/40 text-indigo-700 dark:text-indigo-300',
    tag: '18 phút • Hát ru',
    title: 'Bản Hòa Ca Của Chị Trăng',
    description: 'Những âm điệu dịu êm nhẹ nhàng đưa bé vào thế giới giấc mơ nhiệm màu...',
    rating: 5.0,
    imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=600&auto=format&fit=crop',
    isFavorite: true,
  },
];

export const LIBRARY_BADGES: AchievementBadge[] = [
  {
    id: 'bdg-1',
    icon: '🌊',
    title: 'Thám Hiểm Đại Dương',
    subtitle: 'Đã hoàn thành 5 truyện',
    bgColor: 'bg-sky-100 text-sky-700 dark:bg-sky-900/30 dark:text-sky-300',
  },
  {
    id: 'bdg-2',
    icon: '🚀',
    title: 'Tưởng Tượng Bay Xa',
    subtitle: 'Tạo 3 truyện AI',
    bgColor: 'bg-rose-100 text-rose-700 dark:bg-rose-900/30 dark:text-rose-300',
  },
  {
    id: 'bdg-3',
    icon: '💖',
    title: 'Trái Tim Nhân Ái',
    subtitle: 'Bài học lòng tốt',
    bgColor: 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-300',
  },
];

export const DAY_STREAKS: DayStreakItem[] = [
  { day: 'T2', isCompleted: true },
  { day: 'T3', isCompleted: true },
  { day: 'T4', isCompleted: true },
  { day: 'T5', isCompleted: true },
  { day: 'Hôm nay', isCompleted: false, isCurrent: true },
  { day: 'T7', isCompleted: false, isLocked: true },
  { day: 'CN', isCompleted: false, isLocked: true },
];
