import { StoryCategory, StoryItem, LullabySound } from '../types/home';
import { FeaturedTopic, ShowcaseCollection, ExploreStoryItem } from '../types/explore';
import { LibraryStoryItem, AchievementBadge, DayStreakItem } from '../types/library';

export const CATEGORIES: StoryCategory[] = [
  {
    id: 'space',
    title: 'Vũ Trụ Phiêu Lưu',
    count: '240+ truyện',
    icon: '🚀',
    bgGradient: 'from-sky-50 to-blue-100/70',
    borderColor: 'border-sky-200',
    textColor: 'text-sky-800',
    badgeBg: 'bg-sky-100 text-sky-700',
  },
  {
    id: 'magic',
    title: 'Cổ Tích Phép Thuật',
    count: '310+ truyện',
    icon: '🪄',
    bgGradient: 'from-pink-50 to-rose-100/70',
    borderColor: 'border-pink-200',
    textColor: 'text-pink-800',
    badgeBg: 'bg-pink-100 text-pink-700',
  },
  {
    id: 'animals',
    title: 'Thế Giới Động Vật',
    count: '320+ truyện',
    icon: '🐸',
    bgGradient: 'from-emerald-50 to-teal-100/70',
    borderColor: 'border-emerald-200',
    textColor: 'text-emerald-800',
    badgeBg: 'bg-emerald-100 text-emerald-700',
  },
  {
    id: 'prehistoric',
    title: 'Thời Tiền Sử',
    count: '85+ truyện',
    icon: '🦖',
    bgGradient: 'from-amber-50 to-yellow-100/70',
    borderColor: 'border-amber-200',
    textColor: 'text-amber-800',
    badgeBg: 'bg-amber-100 text-amber-700',
  },
  {
    id: 'ocean',
    title: 'Đáy Đại Dương',
    count: '195+ truyện',
    icon: '🐳',
    bgGradient: 'from-cyan-50 to-blue-100/70',
    borderColor: 'border-cyan-200',
    textColor: 'text-cyan-800',
    badgeBg: 'bg-cyan-100 text-cyan-700',
  },
  {
    id: 'life-lessons',
    title: 'Bài Học Cuộc Sống',
    count: '380+ truyện',
    icon: '🥑',
    bgGradient: 'from-rose-50 to-orange-100/70',
    borderColor: 'border-rose-200',
    textColor: 'text-rose-800',
    badgeBg: 'bg-rose-100 text-rose-700',
  },
];

export const TRENDING_STORIES: StoryItem[] = [
  {
    id: '1',
    title: 'Lâu Đài Kẹo Ngọt Trên Mây',
    description: 'Cùng bé An và thỏ Trắng học cách sẻ chia kẹo ngọt để giải cứu vương quốc trên mây khỏi nguy cơ bị rã tan...',
    duration: '10 phút',
    tag: 'AI & Bé An sáng tạo',
    tagColor: 'bg-amber-100 text-amber-800 border-amber-200',
    listens: '4.3k',
    rating: 4.9,
    imageUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=600&auto=format&fit=crop',
    actionText: 'Nghe ngay',
    actionType: 'play',
    isFavorite: true,
  },
  {
    id: '2',
    title: 'Khủng Long Dino Đi Tìm Mẹ',
    description: 'Hành trình dũng cảm băng qua thung lũng đá núi lửa và kết bạn với những chú rồng biết bay thông thái...',
    duration: '8 phút',
    tag: 'Âm thanh sống động',
    tagColor: 'bg-orange-100 text-orange-800 border-orange-200',
    listens: '9.2k',
    rating: 5.0,
    imageUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?q=80&w=600&auto=format&fit=crop',
    actionText: 'Đọc & Nghe',
    actionType: 'read',
    isFavorite: true,
  },
  {
    id: '3',
    title: 'Chuyến Phiêu Lưu Đáy Biển Của Rùa Con',
    description: 'Bài học về bảo vệ rạn san hô và dọn sạch rác thải nhựa cùng những người bạn cá heo vui tính dưới đại dương...',
    duration: '12 phút',
    tag: 'Giáo dục bảo vệ biển',
    tagColor: 'bg-cyan-100 text-cyan-800 border-cyan-200',
    listens: '2.7k',
    rating: 4.8,
    imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=600&auto=format&fit=crop',
    actionText: 'Nghe ngay',
    actionType: 'play',
    isFavorite: true,
  },
  {
    id: '4',
    title: 'Chiếc Ô Bay Của Phù Thủy Nhỏ',
    description: 'Chiếc ô thần kỳ có thể che mưa cho cả khu rừng và biến những hạt mưa thành kẹo ngọt màu sắc làm quà cho động vật...',
    duration: '7 phút',
    tag: 'Trí tưởng tượng bay bổng',
    tagColor: 'bg-purple-100 text-purple-800 border-purple-200',
    listens: '5.1k',
    rating: 4.9,
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=600&auto=format&fit=crop',
    actionText: 'Đọc & Nghe',
    actionType: 'read',
    isFavorite: true,
  },
];

export const LULLABY_SOUNDS: LullabySound[] = [
  { id: 'rain', name: 'Tiếng mưa rơi rỉ rách', icon: '🌧️' },
  { id: 'waves', name: 'Sóng biển rì rào', icon: '🌊' },
  { id: 'crickets', name: 'Dế mèn hát đêm', icon: '🎶' },
];

// Explore Page Mock Data
export const FEATURED_TOPICS: FeaturedTopic[] = [
  {
    id: 'magic',
    title: 'Cổ Tích & Phép Thuật',
    count: '1.450 truyện',
    icon: '🪄',
    colorBg: 'bg-amber-100 dark:bg-amber-900/30 text-amber-600 dark:text-amber-400',
    cardBorder: 'border-amber-200/60 dark:border-amber-800/40',
    hoverBg: 'hover:border-amber-400',
  },
  {
    id: 'space',
    title: 'Vũ Trụ & Khoa Học',
    count: '850 truyện',
    icon: '🚀',
    colorBg: 'bg-indigo-100 dark:bg-indigo-900/30 text-indigo-600 dark:text-indigo-400',
    cardBorder: 'border-indigo-200/60 dark:border-indigo-800/40',
    hoverBg: 'hover:border-indigo-400',
  },
  {
    id: 'animals',
    title: 'Thế Giới Động Vật',
    count: '1.120 truyện',
    icon: '🐸',
    colorBg: 'bg-emerald-100 dark:bg-emerald-900/30 text-emerald-600 dark:text-emerald-400',
    cardBorder: 'border-emerald-200/60 dark:border-emerald-800/40',
    hoverBg: 'hover:border-emerald-400',
  },
  {
    id: 'emotions',
    title: 'Bài Học Cảm Xúc',
    count: '640 truyện',
    icon: '💖',
    colorBg: 'bg-rose-100 dark:bg-rose-900/30 text-rose-600 dark:text-rose-400',
    cardBorder: 'border-rose-200/60 dark:border-rose-800/40',
    hoverBg: 'hover:border-rose-400',
  },
  {
    id: 'lullaby',
    title: 'Ru Ngủ & Thư Giãn',
    count: '520 truyện',
    icon: '🌙',
    colorBg: 'bg-amber-100 dark:bg-amber-900/30 text-amber-600 dark:text-amber-400',
    cardBorder: 'border-amber-200/60 dark:border-amber-800/40',
    hoverBg: 'hover:border-amber-400',
  },
  {
    id: 'adventure',
    title: 'Thám Hiểm & Kỳ Thú',
    count: '930 truyện',
    icon: '🧭',
    colorBg: 'bg-teal-100 dark:bg-teal-900/30 text-teal-600 dark:text-teal-400',
    cardBorder: 'border-teal-200/60 dark:border-teal-800/40',
    hoverBg: 'hover:border-teal-400',
  },
];

export const SHOWCASE_COLLECTIONS: ShowcaseCollection[] = [
  {
    id: 'lullaby-set',
    tag: '🌙 GIẤC NGỦ NGỌT NGÀO',
    count: '24 truyện',
    title: 'Tuyển Tập Truyện Ru Ngủ Dịu Êm',
    description: 'Kết hợp âm thanh sóng nào Alpha và giọng đọc thủ thỉ dịu êm, vỗ về bé vào giấc mộng thần tiên sau 15 phút.',
    ages: ['2', '3', '4'],
    badgeBg: 'bg-amber-100 dark:bg-amber-900/40 text-amber-700 dark:text-amber-300',
    cardBg: 'from-amber-50/80 via-amber-100/30 to-surface-container-lowest dark:from-amber-950/20 dark:to-surface-container-lowest',
    accentBorder: 'border-amber-300/60 dark:border-amber-800/50',
    btnBg: 'bg-amber-500 hover:bg-amber-600 text-white',
  },
  {
    id: 'eq-set',
    tag: '🛡️ RÈN LUYỆN EQ & NHÂN ÁI',
    count: '18 truyện',
    title: 'Bài Học Về Lòng Dũng Cảm & Sẻ Chia',
    description: 'Những câu chuyện phiêu lưu kỳ thú giúp bé học cách đối diện, đối xử tử tế và biết chia sẻ với bạn bè xung quanh.',
    ages: ['5', '6', '7'],
    badgeBg: 'bg-rose-100 dark:bg-rose-900/40 text-rose-700 dark:text-rose-300',
    cardBg: 'from-rose-50/80 via-rose-100/30 to-surface-container-lowest dark:from-rose-950/20 dark:to-surface-container-lowest',
    accentBorder: 'border-rose-300/60 dark:border-rose-800/50',
    btnBg: 'bg-rose-500 hover:bg-rose-600 text-white',
  },
  {
    id: 'stem-set',
    tag: '🧪 TƯ DUY KHOA HỌC STEM',
    count: '32 truyện',
    title: 'Chuyến Thám Hiểm Khoa Học Kỳ Thú',
    description: 'Giải đáp mọi câu hỏi vì sao: Tại sao bầu trời có màu xanh? Hạt mưa từ đâu tới? Hành trình của vạn vật như thế nào?',
    ages: ['8', '9', '10'],
    badgeBg: 'bg-teal-100 dark:bg-teal-900/40 text-teal-700 dark:text-teal-300',
    cardBg: 'from-teal-50/80 via-teal-100/30 to-surface-container-lowest dark:from-teal-950/20 dark:to-surface-container-lowest',
    accentBorder: 'border-teal-300/60 dark:border-teal-800/50',
    btnBg: 'bg-teal-600 hover:bg-teal-700 text-white',
  },
];

export const EXPLORE_STORY_LIST: ExploreStoryItem[] = [
  {
    id: 'st-1',
    categoryTag: 'Cổ tích • 5-7 tuổi',
    title: 'Lâu Đài Kẹo Ngọt Trên Mây',
    description: 'Bé An cùng các người bạn thần tiên giải cứu vương quốc kẹo ngọt và học bài học quý giá về lòng tốt...',
    badgeText: '✨ Tương tác trí tuệ',
    badgeColor: 'bg-amber-100 dark:bg-amber-900/40 text-amber-700 dark:text-amber-300',
    duration: '6 phút',
    rating: 4.9,
    listens: '1.2k',
    imageUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=600&auto=format&fit=crop',
    actionText: 'Đọc & Nghe ngay',
  },
  {
    id: 'st-2',
    categoryTag: 'Phiêu lưu • 3-5 tuổi',
    title: 'Khủng Long Dino Đi Tìm Nắng',
    description: 'Dino con sưởi ấm tâm hồn bạn bè trong thung lũng lạnh và cùng học cách yêu thương thiên nhiên...',
    badgeText: '🟢 Giọng miền Nam',
    badgeColor: 'bg-emerald-100 dark:bg-emerald-900/40 text-emerald-700 dark:text-emerald-300',
    duration: '8 phút',
    rating: 4.8,
    listens: '950',
    imageUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?q=80&w=600&auto=format&fit=crop',
    actionText: 'Đọc & Nghe ngay',
  },
  {
    id: 'st-3',
    categoryTag: 'Đại dương • 4-6 tuổi',
    title: 'Chuyến Phiêu Lưu Của Rùa Con',
    description: 'Đánh tan cơn bão biển đông cùng rùa biển thông thái và giải cứu các sinh vật đại dương xinh đẹp...',
    badgeText: '✨ Tương tác trí tuệ',
    badgeColor: 'bg-amber-100 dark:bg-amber-900/40 text-amber-700 dark:text-amber-300',
    duration: '12 phút',
    rating: 5.0,
    listens: '2.3k',
    imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=600&auto=format&fit=crop',
    actionText: 'Đọc & Nghe ngay',
  },
  {
    id: 'st-4',
    categoryTag: 'Phép thuật • 6-8 tuổi',
    title: 'Chiếc Ô Bay Của Phù Thủy Nhỏ',
    description: 'Đốt cháy ước mơ bay đến vì sao xa cùng phù thủy nhỏ tốt bụng và chiếc ô kỳ diệu che chở muôn loài...',
    badgeText: '🎵 Nhạc âm dịu',
    badgeColor: 'bg-indigo-100 dark:bg-indigo-900/40 text-indigo-700 dark:text-indigo-300',
    duration: '7 phút',
    rating: 4.9,
    listens: '850',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=600&auto=format&fit=crop',
    actionText: 'Đọc & Nghe ngay',
  },
  {
    id: 'st-5',
    categoryTag: 'Vũ trụ • 7-10 tuổi',
    title: 'Chuyến Tàu Ngân Hà Xứ Mộng',
    description: 'Chuyến du hành vượt dải ngân hà rộng lớn cùng tàu con thoi khám phá những hành tinh ngọt ngào bí ẩn...',
    badgeText: '🚀 Âm thanh hành tinh',
    badgeColor: 'bg-purple-100 dark:bg-purple-900/40 text-purple-700 dark:text-purple-300',
    duration: '15 phút',
    rating: 4.95,
    listens: '2.1k',
    imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=600&auto=format&fit=crop',
    actionText: 'Đọc & Nghe ngay',
  },
  {
    id: 'st-6',
    categoryTag: 'Động vật • 4-7 tuổi',
    title: 'Bác Sĩ Cú Mèo & Khu Rừng Xanh',
    description: 'Bác sĩ Cú Mèo điều trị bệnh biếng ăn cho thỏ con và truyền cảm hứng lối sống lành mạnh đến cả khu rừng...',
    badgeText: '🟢 Giọng Trầm Ấm',
    badgeColor: 'bg-teal-100 dark:bg-teal-900/40 text-teal-700 dark:text-teal-300',
    duration: '9 phút',
    rating: 4.9,
    listens: '670',
    imageUrl: 'https://images.unsplash.com/photo-1543549790-8b5f4a028cfb?q=80&w=600&auto=format&fit=crop',
    actionText: 'Đọc & Nghe ngay',
  },
  {
    id: 'st-7',
    categoryTag: 'Cảm xúc • 5-8 tuổi',
    title: 'Bí Ẩn Của Chú Cáo Đỏ',
    description: 'Hành trình tìm lại sự tự tin và lòng tin của chú cáo nhỏ khi chuyển tới ngôi trường mới ở rừng xanh...',
    badgeText: '✨ Tương tác',
    badgeColor: 'bg-rose-100 dark:bg-rose-900/40 text-rose-700 dark:text-rose-300',
    duration: '10 phút',
    rating: 4.85,
    listens: '1.1k',
    imageUrl: 'https://images.unsplash.com/photo-1474511320723-9a56873867b5?q=80&w=600&auto=format&fit=crop',
    actionText: 'Đọc & Nghe ngay',
  },
  {
    id: 'st-8',
    categoryTag: 'Ru ngủ • 2-5 tuổi',
    title: 'Bản Hòa Ca Của Chị Hằng',
    description: 'Những giai điệu du dương hòa cùng câu chuyện chị Hằng đưa bé chìm vào giấc ngủ êm đềm bình yên...',
    badgeText: '🎵 Giọng ru êm dịu',
    badgeColor: 'bg-amber-100 dark:bg-amber-900/40 text-amber-700 dark:text-amber-300',
    duration: '18 phút',
    rating: 5.0,
    listens: '3.4k',
    imageUrl: 'https://images.unsplash.com/photo-1532693322450-2cb5c511067d?q=80&w=600&auto=format&fit=crop',
    actionText: 'Đọc & Nghe ngay',
  },
];

// Library Page Mock Data
export const LIBRARY_CREATED_STORIES: LibraryStoryItem[] = [
  {
    id: 'cr-1',
    badge: '🤖 AI Mini & Bé Bo',
    badgeBg: 'bg-emerald-100 dark:bg-emerald-900/40 text-emerald-700 dark:text-emerald-300',
    tag: 'Sáng tạo ngày 12/03 • 8 phút nghe',
    title: 'Chiếc Bánh Quy Biết Bay Của Thỏ Bông',
    description: 'Chú thỏ Bông nhặt được số phép thuật nấu nướng, nướng ra chiếc bánh quy có cánh bay khắp xóm làng...',
    imageUrl: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?q=80&w=600&auto=format&fit=crop',
    isFavorite: true,
  },
  {
    id: 'cr-2',
    badge: '🎨 Bé Bo đồng tác giả',
    badgeBg: 'bg-amber-100 dark:bg-amber-900/40 text-amber-700 dark:text-amber-300',
    tag: 'Sáng tạo ngày 09/03 • 12 phút nghe',
    title: 'Khủng Long Dino Đi Tìm Mẹ Thần Tiên',
    description: 'Dino dũng cảm chế tạo đá bay kỳ ảo rực rỡ nắng lồng, vượt qua rừng thung thạch ngọt ngào để tìm thấy mẹ...',
    imageUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?q=80&w=600&auto=format&fit=crop',
    isFavorite: true,
  },
];

export const LIBRARY_FAVORITE_STORIES: LibraryStoryItem[] = [
  {
    id: 'fav-1',
    badge: '🌙 Ru ngủ sâu',
    badgeBg: 'bg-indigo-100 dark:bg-indigo-900/40 text-indigo-700 dark:text-indigo-300',
    tag: '15 phút • Sóng Alpha',
    title: 'Chuyến Du Hành Vào Giấc Mộng',
    description: 'Giai điệu du dương hòa cùng giọng hát ru vỗ về bé vào giấc ngủ ngon êm đềm...',
    rating: 5.0,
    imageUrl: 'https://images.unsplash.com/photo-1532693322450-2cb5c511067d?q=80&w=600&auto=format&fit=crop',
    isFavorite: true,
  },
  {
    id: 'fav-2',
    badge: '🌲 Giáo dục tâm hồn',
    badgeBg: 'bg-emerald-100 dark:bg-emerald-900/40 text-emerald-700 dark:text-emerald-300',
    tag: '10 phút • Giọng ấm',
    title: 'Bác Sĩ Cú Mèo & Khu Rừng Xanh',
    description: 'Bác sĩ Cú Mèo chữa lành tâm hồn thỏ con và dạy bài học yêu thương bạn bè...',
    rating: 4.9,
    imageUrl: 'https://images.unsplash.com/photo-1543549790-8b5f4a028cfb?q=80&w=600&auto=format&fit=crop',
    isFavorite: true,
  },
  {
    id: 'fav-3',
    badge: '🪄 Phép thuật',
    badgeBg: 'bg-amber-100 dark:bg-amber-900/40 text-amber-700 dark:text-amber-300',
    tag: '12 phút • Nghe trước ngủ',
    title: 'Chiếc Ô Bay Của Phù Thủy Nhỏ',
    description: 'Chiếc ô thần kỳ che chở muôn loài và mở ra vùng đất diệu kỳ cho ước mơ của bé...',
    rating: 4.9,
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=600&auto=format&fit=crop',
    isFavorite: true,
  },
  {
    id: 'fav-4',
    badge: '🌙 Ru ngủ sâu',
    badgeBg: 'bg-indigo-100 dark:bg-indigo-900/40 text-indigo-700 dark:text-indigo-300',
    tag: '18 phút • Hát ru',
    title: 'Bản Hòa Ca Của Chị Trăng',
    description: 'Những âm điệu dịu êm nhẹ nhàng đưa bé vào thế giới giấc mơ nhiệm màu...',
    rating: 5.0,
    imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=600&auto=format&fit=crop',
    isFavorite: true,
  },
];

export const LIBRARY_BADGES: AchievementBadge[] = [
  {
    id: 'bdg-1',
    icon: '🌊',
    title: 'Thám Hiểm Đại Dương',
    subtitle: 'Đã hoàn thành 5 truyện',
    bgColor: 'bg-sky-100 text-sky-700 dark:bg-sky-900/30 dark:text-sky-300',
  },
  {
    id: 'bdg-2',
    icon: '🚀',
    title: 'Tưởng Tượng Bay Xa',
    subtitle: 'Tạo 3 truyện AI',
    bgColor: 'bg-rose-100 text-rose-700 dark:bg-rose-900/30 dark:text-rose-300',
  },
  {
    id: 'bdg-3',
    icon: '💖',
    title: 'Trái Tim Nhân Ái',
    subtitle: 'Bài học lòng tốt',
    bgColor: 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-300',
  },
];

export const DAY_STREAKS: DayStreakItem[] = [
  { day: 'T2', isCompleted: true },
  { day: 'T3', isCompleted: true },
  { day: 'T4', isCompleted: true },
  { day: 'T5', isCompleted: true },
  { day: 'Hôm nay', isCompleted: false, isCurrent: true },
  { day: 'T7', isCompleted: false, isLocked: true },
  { day: 'CN', isCompleted: false, isLocked: true },
];
