import { StoryCategory, StoryItem, LullabySound } from '../types/home';

export const CATEGORIES: StoryCategory[] = [
  {
    id: 'space',
    title: 'Vũ Trụ Phiêu Lưu',
    count: '240+ truyện',
    icon: '🚀',
    bgGradient: 'from-sky-50 to-blue-100/70',
    borderColor: 'border-sky-200',
    textColor: 'text-sky-800',
    badgeBg: 'bg-sky-100 text-sky-700',
  },
  {
    id: 'magic',
    title: 'Cổ Tích Phép Thuật',
    count: '310+ truyện',
    icon: '🪄',
    bgGradient: 'from-pink-50 to-rose-100/70',
    borderColor: 'border-pink-200',
    textColor: 'text-pink-800',
    badgeBg: 'bg-pink-100 text-pink-700',
  },
  {
    id: 'animals',
    title: 'Thế Giới Động Vật',
    count: '320+ truyện',
    icon: '🐸',
    bgGradient: 'from-emerald-50 to-teal-100/70',
    borderColor: 'border-emerald-200',
    textColor: 'text-emerald-800',
    badgeBg: 'bg-emerald-100 text-emerald-700',
  },
  {
    id: 'prehistoric',
    title: 'Thời Tiền Sử',
    count: '85+ truyện',
    icon: '🦖',
    bgGradient: 'from-amber-50 to-yellow-100/70',
    borderColor: 'border-amber-200',
    textColor: 'text-amber-800',
    badgeBg: 'bg-amber-100 text-amber-700',
  },
  {
    id: 'ocean',
    title: 'Đáy Đại Dương',
    count: '195+ truyện',
    icon: '🐳',
    bgGradient: 'from-cyan-50 to-blue-100/70',
    borderColor: 'border-cyan-200',
    textColor: 'text-cyan-800',
    badgeBg: 'bg-cyan-100 text-cyan-700',
  },
  {
    id: 'life-lessons',
    title: 'Bài Học Cuộc Sống',
    count: '380+ truyện',
    icon: '🥑',
    bgGradient: 'from-rose-50 to-orange-100/70',
    borderColor: 'border-rose-200',
    textColor: 'text-rose-800',
    badgeBg: 'bg-rose-100 text-rose-700',
  },
];

export const TRENDING_STORIES: StoryItem[] = [
  {
    id: '1',
    title: 'Lâu Đài Kẹo Ngọt Trên Mây',
    description: 'Cùng bé An và thỏ Trắng học cách sẻ chia kẹo ngọt để giải cứu vương quốc trên mây khỏi nguy cơ bị rã tan...',
    duration: '10 phút',
    tag: 'AI & Bé An sáng tạo',
    tagColor: 'bg-amber-100 text-amber-800 border-amber-200',
    listens: '4.3k',
    rating: 4.9,
    imageUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=600&auto=format&fit=crop',
    actionText: 'Nghe ngay',
    actionType: 'play',
    isFavorite: true,
  },
  {
    id: '2',
    title: 'Khủng Long Dino Đi Tìm Mẹ',
    description: 'Hành trình dũng cảm băng qua thung lũng đá núi lửa và kết bạn với những chú rồng biết bay thông thái...',
    duration: '8 phút',
    tag: 'Âm thanh sống động',
    tagColor: 'bg-orange-100 text-orange-800 border-orange-200',
    listens: '9.2k',
    rating: 5.0,
    imageUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?q=80&w=600&auto=format&fit=crop',
    actionText: 'Đọc & Nghe',
    actionType: 'read',
    isFavorite: true,
  },
  {
    id: '3',
    title: 'Chuyến Phiêu Lưu Đáy Biển Của Rùa Con',
    description: 'Bài học về bảo vệ rạn san hô và dọn sạch rác thải nhựa cùng những người bạn cá heo vui tính dưới đại dương...',
    duration: '12 phút',
    tag: 'Giáo dục bảo vệ biển',
    tagColor: 'bg-cyan-100 text-cyan-800 border-cyan-200',
    listens: '2.7k',
    rating: 4.8,
    imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=600&auto=format&fit=crop',
    actionText: 'Nghe ngay',
    actionType: 'play',
    isFavorite: true,
  },
  {
    id: '4',
    title: 'Chiếc Ô Bay Của Phù Thủy Nhỏ',
    description: 'Chiếc ô thần kỳ có thể che mưa cho cả khu rừng và biến những hạt mưa thành kẹo ngọt màu sắc làm quà cho động vật...',
    duration: '7 phút',
    tag: 'Trí tưởng tượng bay bổng',
    tagColor: 'bg-purple-100 text-purple-800 border-purple-200',
    listens: '5.1k',
    rating: 4.9,
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=600&auto=format&fit=crop',
    actionText: 'Đọc & Nghe',
    actionType: 'read',
    isFavorite: true,
  },
];

export const LULLABY_SOUNDS: LullabySound[] = [
  { id: 'rain', name: 'Tiếng mưa rơi rỉ rách', icon: '🌧️' },
  { id: 'waves', name: 'Sóng biển rì rào', icon: '🌊' },
  { id: 'crickets', name: 'Dế mèn hát đêm', icon: '🎶' },
];
